[general]
admins = ["iButton_0"]
failed_logins = 1
journal_file = arm-abi.log
vnc_addr = 127.0.0.1
vnc_port = 5901
vnc_url = http://127.0.0.1:6080/vnc_lite.html?scale=true
users = [{"id": "iButton_1", "user_name": "Максимов", "passwd_datetime": "12:43 2026/04/07", "last_login_datetime": "00:00 1970/01/01", "total_logins": 0, "failed_logins": 0, "ext_media_prohib": false, "ch_passwd_prohib": false, "passwd_age_limit": false, "user_id_change": false, "user_status": 0, "integrity_ctl_mode": 0}]

[window]
title = ПАК "Соболь" АРМ-АБИ
state = 0
geometry = 22;63;1200;763

[event_journal_panel]
events_end_time_line_edit = 
events_start_time_line_edit = 
events_time_search_check_box = False
events_type_search_check_box = True
file_name_line_edit = 
journal_audit_period_combo_box = 0
journal_max_size_line_edit = 1000
journal_messages_overwriting_check_box = False
volume_combo_box = -1
evet_type_filter = [0, 1]

[sys_load_panel]
port_ctl_check_box = False
serial_ctl_check_box = False
trusted_loader_check_box = True

[common_parms_panel]
alrorithm_combo_box = 0
autologon_time_line_edit = 0
max_failed_logons_line_edit = 10
max_records_combo_box = 0
rnd_testing_attempt_line_edit = 3
show_stats_check_box = True
sound_signals_check_box = False
time_limit_line_edit = 5
timer_testing_period_line_edit = 0
wait_timer_line_edit = 21

[passwd_parms_panel]
changed_symbols_lineedit = 
digit_present_check_box = True
lowercase_letter_check_box = True
min_passwd_len_line_edit = 8
passwd_age_line_edit = 
passwd_difficulty_check_box = True
repeating_char_check_box = False
repeating_digit_check_box = False
special_char_check_box = True
upcase_letter_check_box = True

[integrity_control_panel]
files_ctl_check_box = False
journal_ctl_check_box = False
pci_dev_ctl_combo_box = 0
registry_ctl_check_box = False
sectors_ctl_check_box = False
smbios_ctl_check_box = False
templates_ctl_software_combo_box = 0
templates_dir_line_edit = /sobol
templates_volume_combo_box = -1

